qlib_init:
    provider_uri: "scripts/data_collector/akshare/qlib_data"
    region: cn
market: &market all
benchmark: &benchmark SH000001
data_handler_config: &data_handler_config
    start_time: 2024-01-01
    end_time: 2024-03-31
    fit_start_time: 2024-01-01
    fit_end_time: 2024-02-29
    instruments: *market
    # Explicit label configuration (Alpha158 default)
    label: ["Ref($close, -2)/Ref($close, -1) - 1"]
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              col_list: ["RESI5", "WVMA5", "RSQR5", "KLEN", "RSQR10", "CORR5", "CORD5", "CORR10", 
                            "ROC60", "RESI10", "VSTD5", "RSQR60", "CORR60", "WVMA60", "STD5", 
                            "RSQR20", "CORD60", "CORD10", "CORR20", "KLOW"
                        ]
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
          kwargs: {}
        - class: CSRankNorm
          kwargs:
              fields_group: label

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 10
            n_drop: 2
    backtest:
        start_time: 2024-03-01
        end_time: 2024-03-31
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5

task:
    model:
        class: TransformerModel
        module_path: qlib.contrib.model.pytorch_transformer_ts
        kwargs:
            seed: 0
            n_jobs: 4
            d_feat: 20
            d_model: 64
            n_heads: 4
            num_layers: 3
            dropout: 0.1
            n_epochs: 10
            lr: 0.0001
            metric: loss
            batch_size: 800
            early_stop: 5
            loss: mse
            optimizer: adam
    dataset:
        class: TSDatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2024-01-01, 2024-02-29]
                valid: [2024-03-01, 2024-03-15]
                test: [2024-03-16, 2024-03-31]
            step_len: 20
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
