qlib_init:
    provider_uri: "scripts/data_collector/akshare/qlib_data"
    region: cn

market: &market all
benchmark: &benchmark SH000001

data_handler_config: &data_handler_config
    start_time: 2024-01-01
    end_time: 2024-03-31
    instruments: *market
    data_loader:
        class: QlibDataLoader
        module_path: qlib.data.dataset.loader
        kwargs:
            config:
                feature: ["$open", "$high", "$low", "$close", "$volume"]
                label: ["Ref($close, -1)/$close - 1"]
    infer_processors:
        - class: ProcessInf
        - class: ZScoreNorm
          kwargs:
            fit_start_time: 2024-01-01
            fit_end_time: 2024-02-29
            fields_group: feature
        - class: Fillna
          kwargs:
            fields_group: feature
            fill_value: 0
    learn_processors:
        - class: DropnaLabel

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 2
            n_drop: 0
    backtest:
        start_time: 2024-03-01
        end_time: 2024-03-31
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5

task:
    model:
        class: TransformerModel
        module_path: qlib.contrib.model.pytorch_transformer_ts
        kwargs:
            seed: 0
            n_jobs: 2
            d_feat: 5  # 5 basic features
            d_model: 32
            n_heads: 2
            num_layers: 2
            dropout: 0.1
            n_epochs: 5
            lr: 0.001
            metric: loss
            batch_size: 32
            early_stop: 3
            loss: mse
            optimizer: adam
    dataset:
        class: TSDatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: DataHandlerLP
                module_path: qlib.data.dataset.handler
                kwargs: *data_handler_config
            segments:
                train: [2024-01-02, 2024-02-29]
                valid: [2024-02-15, 2024-02-20]
                test: [2024-03-21, 2024-03-28]
            step_len: 3
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
