qlib_init:
    provider_uri: "scripts/data_collector/akshare/qlib_data"
    region: cn
market: &market all
benchmark: &benchmark SH000001
data_handler_config: &data_handler_config
    start_time: 2022-01-01
    end_time: 2024-12-31
    fit_start_time: 2022-01-01
    fit_end_time: 2023-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              # Enhanced predictive feature set with momentum, volatility, and trend indicators
              col_list: ["KLEN", "KLOW", "KMID", "KUP", "STD5", "STD10", "STD20", "ROC5", "ROC10", "ROC20",
                        "RESI5", "RESI10", "MA5", "MA10", "MA20", "MAX5", "MAX10", "MIN5", "MIN10",
                        "RANK5", "RANK10", "RSV5", "RSV10", "BETA5", "BETA10", "RSQR5", "RSQR10"]
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
              fit_start_time: 2022-01-01
              fit_end_time: 2023-12-31
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    label: ["Ref($close, -2) / Ref($close, -1) - 1"]
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2024-07-01
        end_time: 2024-12-31
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: TransformerModel
        module_path: qlib.contrib.model.pytorch_transformer_ts
        kwargs:
            seed: 0
            n_jobs: 0
            d_feat: 27  # Match the enhanced feature count
            d_model: 128  # Increased model capacity
            nhead: 8  # More attention heads
            num_layers: 4  # Deeper model
            dropout: 0.1  # Reduced dropout for better learning
            n_epochs: 100  # Even more epochs for better convergence
            lr: 0.0005  # Optimal learning rate (not too high)
            metric: loss
            batch_size: 32  # Smaller batch for better gradient updates
            early_stop: 15  # More patience for finding optimal point
            loss: mse
            optimizer: adam
    dataset:
        class: TSDatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158Robust
                module_path: scripts.data_collector.akshare.alpha158_enhanced
                kwargs: *data_handler_config
            segments:
                train: [2022-01-01, 2023-06-30]  # 18 months training
                valid: [2023-07-01, 2023-12-31]  # 6 months validation
                test: [2024-01-01, 2024-12-31]   # 12 months test
            step_len: 20
    record:
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            config: *port_analysis_config
